import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence, useMotionValue, useSpring } from 'framer-motion';
import coupleImg from '@assets/IMG_20260727_155824_1785148270794.jpg';
import giftBoxImg from '@assets/giftbox.png';

const Confetti = () => {
  const pieces = Array.from({ length: 110 }).map((_, i) => ({ id: i, x: (Math.random() - 0.5) * window.innerWidth * 1.35, y: (Math.random() - 1.05) * window.innerHeight, color: ['#f05b8d','#ff9fc2','#ffd1e2','#fff','#f7c6d9','#d94d7c'][Math.floor(Math.random()*6)], rotation: Math.random()*900, scale: Math.random()*1.2+.45, delay: Math.random()*.35 }));
  return <div className="fixed inset-0 pointer-events-none z-[60] flex items-center justify-center overflow-hidden">{pieces.map(p => <motion.div key={p.id} initial={{x:0,y:0,scale:0,rotate:0,opacity:1}} animate={{x:p.x,y:p.y,scale:[0,p.scale,p.scale*.65,0],rotate:p.rotation,opacity:[1,1,.8,0]}} transition={{duration:4,ease:'easeOut',delay:p.delay}} className="absolute h-3 w-3 md:h-4 md:w-4 rounded-sm" style={{backgroundColor:p.color}} />)}</div>;
};

const ESCAPE_MOVES = [{x:180,y:-80,rotate:-15},{x:-200,y:60,rotate:20},{x:120,y:130,rotate:-10},{x:-150,y:-110,rotate:25},{x:220,y:40,rotate:-20},{x:-90,y:140,rotate:30},{x:160,y:-130,rotate:-25},{x:-220,y:-50,rotate:15},{x:80,y:160,rotate:-30},{x:-170,y:100,rotate:22}];
interface RunawayNoProps { onActualClick: () => void; }
const RunawayNo: React.FC<RunawayNoProps> = ({onActualClick}) => {
  const [escapeIndex,setEscapeIndex]=useState(0); const [escapeCount,setEscapeCount]=useState(0); const lastEscape=useRef(0);
  const x=useMotionValue(0), y=useMotionValue(0); const springX=useSpring(x,{stiffness:300,damping:20}), springY=useSpring(y,{stiffness:300,damping:20});
  const escape=useCallback(()=>{const now=Date.now();if(now-lastEscape.current<250)return;lastEscape.current=now;const next=(escapeIndex+1)%ESCAPE_MOVES.length;setEscapeIndex(next);setEscapeCount(c=>c+1);const move=ESCAPE_MOVES[next];x.set(Math.min(Math.abs(move.x),200)*Math.sign(move.x));y.set(Math.min(Math.abs(move.y),150)*Math.sign(move.y));},[escapeIndex,x,y]);
  return <motion.button style={{x:springX,y:springY,rotate:ESCAPE_MOVES[escapeIndex]?.rotate??0,position:'relative',zIndex:10}} onMouseEnter={escape} onMouseMove={escape} onTouchStart={escape} onClick={onActualClick} whileTap={{scale:.9}} className="px-14 py-5 border-2 border-muted-foreground/30 text-muted-foreground rounded-full font-sans text-xl font-medium tracking-widest uppercase select-none cursor-pointer" title={escapeCount>3?"She'll never catch me!":undefined}>No</motion.button>;
};

const RevealParticles=()=> <div className="absolute inset-0 pointer-events-none z-[80] overflow-visible">{Array.from({length:28}).map((_,i)=>{const angle=i/28*Math.PI*2,distance=85+(i%5)*24;return <motion.span key={i} initial={{x:0,y:10,scale:0,opacity:0}} animate={{x:Math.cos(angle)*distance,y:Math.sin(angle)*distance-70,scale:[0,1,0],opacity:[0,1,0],rotate:360}} transition={{duration:1.25,ease:'easeOut',delay:i*.018}} className="absolute left-1/2 top-[48%] h-2.5 w-2.5 rounded-full bg-white shadow-[0_0_14px_rgba(255,255,255,.95)]"/>})}</div>;

const RealisticGiftOpening=({coupleImg}:{coupleImg:string})=><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.22}} className="relative w-[min(88vw,500px)] aspect-[2/3] flex items-center justify-center" style={{perspective:1200}}>
  <RevealParticles/>
  <motion.div initial={{opacity:.45,scaleX:1}} animate={{opacity:[.45,.22,.12],scaleX:[1,.92,.82]}} transition={{duration:1.9,ease:'easeOut'}} className="absolute bottom-[7%] left-1/2 h-7 w-[56%] -translate-x-1/2 rounded-[50%] bg-black/25 blur-xl"/>
  <motion.img src={giftBoxImg} alt="Pink birthday gift box" draggable={false} initial={{opacity:1}} animate={{opacity:0}} transition={{delay:.08,duration:.18}} className="absolute inset-0 h-full w-full object-contain drop-shadow-[0_28px_28px_rgba(190,70,120,.28)]"/>
  <motion.div initial={{opacity:0,scale:.7}} animate={{opacity:[0,.85,.5,0],scale:[.7,1,1.12,1.3]}} transition={{delay:.12,duration:1.2,ease:'easeOut'}} className="absolute left-1/2 top-[47%] h-[13%] w-[57%] -translate-x-1/2 rounded-[50%] bg-[#6e1d40] blur-md"/>
  <motion.div initial={{opacity:0,scale:.25}} animate={{opacity:[0,.95,.45,0],scale:[.25,.72,1.05,1.28]}} transition={{delay:.2,duration:1.15,ease:'easeOut'}} className="absolute left-1/2 top-[47%] h-[18%] w-[36%] -translate-x-1/2 rounded-full bg-pink-100 blur-3xl pointer-events-none"/>
  <div className="absolute inset-0 overflow-hidden" style={{clipPath:'polygon(0 48%,100% 48%,100% 100%,0 100%)'}}><img src={giftBoxImg} alt="" draggable={false} className="absolute inset-0 h-full w-full object-contain drop-shadow-[0_28px_28px_rgba(190,70,120,.28)]"/></div>
  <motion.div initial={{y:42,opacity:0,scale:.72}} animate={{y:-34,opacity:1,scale:1}} transition={{delay:.7,duration:.82,ease:[.16,1,.3,1]}} className="absolute left-1/2 top-[44%] z-[45] h-[18%] w-[24%] -translate-x-1/2 overflow-hidden rounded-[12px] border-[4px] border-white bg-white shadow-[0_16px_30px_rgba(65,10,35,.35)]"><img src={coupleImg} alt="Your surprise" className="h-full w-full object-cover"/></motion.div>
  <motion.div initial={{y:0,x:0,rotateZ:0,rotateY:0,scale:1,opacity:1}} animate={{y:-105,x:9,rotateZ:-3.2,rotateY:-8,scale:.99,opacity:.98}} transition={{delay:.16,duration:1.05,ease:[.16,1,.3,1]}} className="absolute inset-0 overflow-visible" style={{clipPath:'polygon(0 0,100% 0,100% 49%,0 49%)',transformOrigin:'50% 49%',transformStyle:'preserve-3d',zIndex:50}}><img src={giftBoxImg} alt="" draggable={false} className="absolute inset-0 h-full w-full object-contain drop-shadow-[0_22px_24px_rgba(185,55,110,.32)]"/></motion.div>
  {Array.from({length:7}).map((_,i)=><motion.span key={i} initial={{opacity:0,y:20,x:0,scale:.35}} animate={{opacity:[0,1,0],y:-105-i*8,x:(i-3)*28,scale:[.35,1,.65]}} transition={{delay:.72+i*.07,duration:1.35,ease:'easeOut'}} className="absolute left-1/2 top-[48%] z-[90] text-xl md:text-2xl text-primary">{i%2===0?'♥':'✦'}</motion.span>)}
</motion.div>;

const InteractiveGift=()=>{
  const [clickCount,setClickCount]=useState(0),[isOpening,setIsOpening]=useState(false),[answer,setAnswer]=useState<'yes'|'no'|null>(null),[showConfetti,setShowConfetti]=useState(false);
  const isOpened=clickCount>=3&&!isOpening;
  const handleGiftClick=()=>{if(isOpening||isOpened)return;if(clickCount<2){setClickCount(p=>p+1);return;}setClickCount(3);setIsOpening(true);window.setTimeout(()=>setIsOpening(false),2050);};
  const handleYes=()=>{setAnswer('yes');setShowConfetti(true);window.setTimeout(()=>setShowConfetti(false),5500);};
  const getInstruction=()=>isOpening?'Opening your surprise...':clickCount===0?'Tap the gift to unwrap your surprise':clickCount===1?'The ribbon is coming loose...':'One more tap to open it!';
  return <section className="w-full py-24 md:py-32 flex flex-col items-center justify-center relative min-h-[80vh] overflow-hidden"><div className="absolute inset-0 bg-primary/5 -skew-y-3 z-0"/><div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_50%_45%,rgba(255,150,190,.22),transparent_42%)]"/>{showConfetti&&<Confetti/>}
    <div className="z-10 w-full max-w-5xl px-5 md:px-8 flex flex-col items-center"><AnimatePresence mode="wait">
      {isOpening?<motion.div key="opening" className="flex flex-col items-center w-full"><RealisticGiftOpening coupleImg={coupleImg}/><motion.p initial={{opacity:0,y:8}} animate={{opacity:[.5,1,.5],y:[0,-2,0]}} transition={{duration:.8,repeat:Infinity}} className="mt-1 font-sans text-xs md:text-sm font-semibold uppercase tracking-[.24em] text-primary">Opening your surprise...</motion.p></motion.div>
      :!isOpened?<motion.div key="closed-gift" exit={{opacity:0,scale:.92,y:18}} transition={{duration:.25}} className="flex flex-col items-center cursor-pointer select-none" onClick={handleGiftClick} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')handleGiftClick();}} aria-label="Open your birthday gift">
        <motion.div whileHover={{scale:1.035,rotateZ:-1.2}} animate={clickCount===0?{y:[0,-9,0],rotateZ:[0,-.7,0,.7,0]}:clickCount===1?{rotateZ:[-1.6,1.6,-1.2,0],scale:1.018}:{rotateZ:[-2.2,2.2,-1.6,0],scale:1.035}} transition={{duration:clickCount===0?2.7:.42,repeat:clickCount===0?Infinity:0,ease:'easeInOut'}} className="relative w-[min(78vw,430px)] aspect-square"><motion.div animate={{opacity:[.2,.48,.2],scale:[.94,1.05,.94]}} transition={{duration:2.4,repeat:Infinity,ease:'easeInOut'}} className="absolute left-1/2 top-[50%] h-44 w-44 -translate-x-1/2 -translate-y-1/2 rounded-full bg-pink-300/30 blur-3xl"/><div className="absolute -bottom-1 left-1/2 h-7 w-[58%] -translate-x-1/2 rounded-[50%] bg-black/20 blur-xl"/><img src={giftBoxImg} alt="Pink birthday gift box" draggable={false} className="absolute inset-0 h-full w-full object-contain drop-shadow-[0_28px_28px_rgba(190,70,120,.28)]"/></motion.div>
        <motion.div className="mt-8 md:mt-10 text-center" animate={{opacity:[.55,1,.55]}} transition={{duration:1.8,repeat:Infinity,ease:'easeInOut'}}><p className="font-sans text-xs md:text-sm font-semibold uppercase tracking-[.24em] text-primary">{getInstruction()}</p><div className="mt-3 flex items-center justify-center gap-2">{[0,1,2].map(step=><span key={step} className={`h-1.5 rounded-full transition-all duration-300 ${step<clickCount?'w-8 bg-primary':'w-2 bg-primary/20'}`}/>)}</div></motion.div>
        {clickCount===0&&<motion.div animate={{opacity:[.55,1,.55],y:[0,-2,0]}} transition={{duration:2,repeat:Infinity}} className="mt-5 flex items-center gap-2 rounded-full border border-primary/15 bg-white/55 px-4 py-2 text-xs text-muted-foreground backdrop-blur-sm shadow-sm"><span>✨</span><span>Three little taps. One big surprise.</span><span>💗</span></motion.div>}
      </motion.div>
      :<motion.div key="opened" initial={{opacity:0,scale:.82,y:70}} animate={{opacity:1,scale:1,y:0}} transition={{type:'spring',damping:14,delay:.05}} className="flex flex-col items-center w-full gap-10">
        <motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.8}} className="relative w-full max-w-xl aspect-square rounded-3xl overflow-hidden shadow-2xl ring-4 ring-primary/30 group"><img src={coupleImg} alt="A beautiful moment together" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent"/></motion.div>
        <AnimatePresence mode="wait">{answer===null&&<motion.div key="question" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.7,delay:.2}} className="flex flex-col items-center gap-8 text-center"><h3 className="font-cursive text-5xl md:text-7xl text-primary text-glow leading-tight">Will you be my love forever?</h3><div className="flex gap-8 flex-wrap justify-center items-center" style={{overflow:'visible',minHeight:'80px'}}><motion.button whileHover={{scale:1.08,y:-4}} whileTap={{scale:.93}} onClick={handleYes} className="px-14 py-5 bg-primary text-primary-foreground rounded-full font-sans text-xl font-semibold shadow-[0_0_40px_rgba(186,75,117,.5)] hover:shadow-[0_0_65px_rgba(186,75,117,.75)] transition-all duration-300 tracking-widest uppercase">Yes</motion.button><RunawayNo onActualClick={()=>setAnswer('no')}/></div></motion.div>}{answer==='yes'&&<motion.div key="yes" initial={{opacity:0,scale:.65}} animate={{opacity:1,scale:1}} transition={{type:'spring',damping:11}} className="text-center space-y-4"><h3 className="font-cursive text-6xl md:text-8xl text-primary text-glow">Forever it is.</h3><p className="font-sans text-lg text-muted-foreground">You just made me the happiest person alive, Bhavanika.</p></motion.div>}{answer==='no'&&<motion.div key="no" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="text-center space-y-5"><h3 className="font-serif text-3xl md:text-5xl text-foreground">My heart says... try again.</h3><p className="font-sans text-muted-foreground text-lg">Because some love stories don't accept "no" as an answer.</p><motion.button whileHover={{scale:1.05}} whileTap={{scale:.95}} onClick={()=>setAnswer(null)} className="mt-4 px-10 py-4 bg-primary/10 border border-primary/30 text-primary rounded-full font-sans text-base tracking-widest uppercase hover:bg-primary/20 transition-all duration-300">Let me answer again</motion.button></motion.div>}</AnimatePresence>
      </motion.div>}
    </AnimatePresence></div>
  </section>;
};

export default InteractiveGift;
